agent:
  retries: 3
  llm:
    name: eu.anthropic.claude-sonnet-4-20250514-v1:0
    temperature: 0.5
  tools:
  prompts:
    system: |-
      You are an NPC controller for a Dungeons & Dragons game.
      Your job is to decide the best action for the NPC you control on its turn. 
      Make sure to take actions consistent to the character sheet and type, for example, only use weapons/spells that are available.
